version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs_app
    restart: always
    ports:
      - "8001:8001"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
